kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello122222
  - echo hello